In [ ]:
print("hello")

hello


**list vs numpy array**

**Example of multi with list and array**
1. time comparsion
2. zeros (3,4)
3. ones (2,3)
4. full ((2,2),7)
5. random (2,3)
6. arange (0,10,2)

In [24]:
# zeros
import numpy as np
# arrary 1d
arr = np.zeros(5)+7
print(arr)

# 2d
arr1 = np.zeros((2,3))+7 # 2 row and 3 cols
print(arr1)

[7. 7. 7. 7. 7.]
[[7. 7. 7.]
 [7. 7. 7.]]


In [19]:
# ones
import numpy as np
# array 1d
arr = np.ones(5)
print(arr)

# 2d
arr1 = np.ones((2,3))
print(arr1)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
# full
import numpy as np
# array 1d
arr = np.full((5),7)
print(arr)

# 2d
arr1 = np.full((2,3),7)
print(arr1)

[7 7 7 7 7]
[[7 7 7]
 [7 7 7]]


In [10]:
# numpy | list
import numpy as np
import time as t

# for list
start = t.time()
sum1 = 0
for i in range(1000000):
  sum1 += i*2
end = t.time()
print("for list",sum1,end-start)

# for numpy | array (array work every element | element wise)
start1 = t.time()
sum2 = 0
arr = np.arange(1000000)*2
sum2 = arr.sum()
end1 = t.time()
print("for array ",sum2,end1-start1)

for list 999999000000 0.14605402946472168
for array  999999000000 0.0031502246856689453


In [11]:
import time as t

print(t.time())

1781857826.9162838


**Array properties**

1. shape
2. dimension | direction
3. size
4. dtype

In [34]:
# array opr on zeros | ones | full
import numpy as np
arr = np.zeros(5)
print(arr)
print(arr.shape) # 5
print(arr.ndim) # 1d
print(arr.size) # 5
print(arr.dtype) # float

# 2d
print("2d ones start")
arr1 = np.zeros((3,2))
print(arr1)
print(arr1.shape) # 3,2
print(arr1.ndim) # 2d
print(arr1.size) # 6
print(arr1.dtype) # float

[0. 0. 0. 0. 0.]
(5,)
1
5
float64
2d ones start
[[0. 0.]
 [0. 0.]
 [0. 0.]]
(3, 2)
2
6
float64


**Array Reshaping**

1. reshape()
2. flatten() -> create copy | shallow copy
3. ravel() -> return original | deep copy
4. transpose -> .T -> reverse

In [38]:
# 1d array
import numpy as np
arr = np.arange(6)
print(arr)

# 2d
arr1 = arr.reshape(2,3) # 2 rows and 3 cols
print(arr1)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [60]:
# flatten | copy
import numpy as np
# 2d
arr = np.arange(6)
arr1 = arr.reshape(2,3)
print(arr1)
# flatten
arr_new = arr1.flatten()
arr_new[0] = 100
print(arr1)
print(arr_new)

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]
[100   1   2   3   4   5]


In [61]:
# ravel | original
import numpy as np
# 2d
arr = np.arange(6).reshape(2,3)
print(arr)
# ravel
arr_new1 = arr.ravel()
arr_new1[0] = 200
print(arr)
print(arr_new1)

[[0 1 2]
 [3 4 5]]
[[200   1   2]
 [  3   4   5]]
[200   1   2   3   4   5]


In [68]:
# transpose
import numpy as np
arr = np.arange(9).reshape(3,3)
print(arr)

# transpose
arr1 = arr.transpose()
print(arr1)

#
arr1 = arr.T
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


**Numpy Array operations**

1. slicing for 1d,2d,3d

**Looping with numpy**

1. while loop
2. for loop

**Sorting**

1. sort() for 1d
2. sort() for 2d ,use axis=0-> cols,axis=1-> rows

**Filter**

1. array[Expression]
2. array[array>2] || filter with mask

**Fancy indexing vs np.where()**

1. array(list)
2. array[[0,1,2]]
3. np.where(expression) -> ternary opr
4. np.where(array>2)
5. np.where(array>2,array*2,array)
6. np.where(array>2,"true","false")

**Adding and Removing Data**

1. np.concatenate((arr1,arr2))
2. np.vstack((original,new_row)) add new row
3. np.hstack((original,new_col)) add new col
4. np.delete(arr,index_no) delete element by index number

**Statistical Functions**

1. np.sum(a) -> Sum of all elements

2. np.mean(a) -> Average = Sum of elements / Number of elements

3. np.median(a) -> Middle value after sorting

4. np.min(a) -> Smallest value in array

5. np.max(a) -> Largest value in array

6. np.var(a) mean,difference,square,average | (sum = ddof) -> divide by array length

7. np.std(a) -> Standard Deviation = √Variance -> Measures spread of data

8. np.prod(a) -> Multiplication of all elements

9. np.cumsum(a) -> Cumulative (running) sum

10. np.cumprod(a) -> Cumulative (running) product

11. np.argmin(a) -> Index position of minimum value

12. np.argmax(a) -> Index position of maximum value

13. np.abs(a) -> Converts negative values to positive -> Absolute value (distance from zero)

14. np.unique(a) -> Returns unique values only -> Removes duplicates

15. np.percentile(a, 50) -> Finds percentage-based value -> 50th percentile = Median

16. np.quantile(a, 0.5) -> Similar to percentile -> 0.5 = 50%

17. np.ptp(a) -> Range = Max - Min

18. np.any(a) -> True if at least one value is True